apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coralogix-quota-rules-status
resources:
  - _namespace.yaml
  - github.com/BigRedS/coralogix-quota-rules-status//deploy/k8s?ref=main
  - ingress.yaml
